version: '3.0'
services:
  web:
    build: ./server
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.4"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "5678:5678"
  worker:
    build: ./worker
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/var/docker/webso/redis:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
